addpath ~/Dropbox/MattW/ucsf_eeg
addpath ~/Dropbox/MattW/suit/chaos
addpath ~/Dropbox/MattW/suit/
addpath ~/Dropbox/complexity/ecomplexity
addpath ~/Dropbox/complexity/stat_utils
addpath ~/Dropbox/complexity/utils
addpath ~/Dropbox/complexity/topDir = '/home/nathanael/data/eeg/ucsf/';
saveDir = '/home/nathanael/data/eeg/ucsf_stim';
cd(topDir)
addpath ~/data/eeg/TDT2matexamples

% % TDT tank method
% tankpath = tname
% blockname = 'EEEG'
% events_load = TDT2mat(tankpath,blockname,'TYPE',[2]); 
% %load only epoch data using the general loading engine
% event_times = events_load.epocs.EpBL.onset; 
% %timestamps of event onsets, in seconds -- event in this case is EpBL taken from the struct generated by TDT2mat

sev2mat()

topDir = '/home/nathanael/data/eeg/ucsf/';
cd(topDir)

% ---------------------------------------
% files to save; selection done in R
% see meta_data.R
% ---------------------------------------

wnames = {'160513_Ms1726/T1_R_Uni_35mW', ...
'160513_Ms1726/T1_R_Uni_35mW', ...
'160513_Ms1726/T1_R_Uni_35mW', ...
'160513_Ms1726/T1_R_Uni_35mW', ...
'160513_Ms1726/T2_R_Uni_35mW', ...
'160513_Ms1726/T2_R_Uni_35mW', ...
'160513_Ms1726/T3_R_Uni_35mW', ...
'160513_Ms1726/T3_R_Uni_35mW', ...
'160513_Ms1729/T1_R_Uni_35mW', ...
'160513_Ms1729/T1_R_Uni_35mW', ...
'160513_Ms1731/T1_R_Uni_35mW', ...
'160513_Ms1731/T1_R_Uni_35mW', ...
'160513_Ms1731/T2_R_Uni_35mW', ...
'160513_Ms1731/T2_R_Uni_35mW', ...
'160513_Ms1731/T3_L_Uni_35mW', ...
'160513_Ms1731/T3_L_Uni_35mW', ...
'160513_Ms1731/T3_L_Uni_35mW', ...
'160513_Ms1731/T4_L_Uni_35mW', ...
'160513_Ms1731/T4_L_Uni_35mW', ...
'160513_Ms1735/T1_R_Uni_35mW', ...
'160513_Ms1735/T2_L_Uni_35mW', ...
'160513_Ms1735/T3_L_Uni_35mW', ...
'160513_Ms1735/T3_L_Uni_35mW', ...
'160513_Ms1735/T3_L_Uni_35mW', ...
'160517_DSY1729/T1_R_Uni_35mW', ...
'160517_DSY1729/T1_R_Uni_35mW', ...
'160517_DSY1729/T1_R_Uni_35mW', ...
'160912_DSY1726/T2_L_Uni_30mW', ...
'160912_DSY1726/T2_L_Uni_30mW', ...
'160912_DSY1726/T2_L_Uni_30mW', ...
'160912_DSY1726/T3_L_Uni_30mW', ...
'160912_DSY1726/T3_L_Uni_30mW', ...
'160912_DSY1726/T3_L_Uni_30mW', ...
'160912_DSY1726/T4_L_Uni_30mW', ...
'160912_DSY1726/T4_L_Uni_30mW', ...
'160912_DSY1726/T4_L_Uni_30mW'};


% saveDir = '/home/nathanael/data/eeg/ucsf_stim';
% saveDir = '/home/nathanael/data/eeg/ucsf_stimplus';
saveDir = '/home/nathanael/data/eeg/ucsf_after_stim';

topDir = '/home/nathanael/data/eeg/ucsf/';

% windows from meta_data.R
fn =  '/home/nathanael/data/eeg/meta/windows.txt';
fID = fopen(fn);
formatSpec = '  %f %f';
sizeA = [2 Inf];
wins = fscanf(fID,formatSpec, sizeA); 
wins = wins';
fclose(fID) 

% 
fs = 1220.7;
% add window after stimulus
winplus = zeros(size(wins));
for k = 1:size(wins, 1) 
  if( wins(k, 2) + 120 <  wins(k + 1, 2 ))
    disp('add, /n')
     winplus(k,:) = [wins(k, 2), wins(k, 2)+120]
  end
end 
winplusfs = winplus*fs
winsfs = wins*fs

%  Save slices from EEG and LFP files
curName = wnames{1}

afterStim = true
temp = strcat(topDir, wnames{k})
data = SEV2mat(temp);
j = 0
for k = 20:size(wnames, 2) %size(wnames,2)
  % handle repeat files
  if(strcmp(curName, wnames{k}))
    j = j + 1
  else
    j = 1
    temp = strcat(topDir, wnames{k})
    data = SEV2mat(temp);
    curName = wnames{k}
  end
  
  % afterstim version
  aa  = floor(winplusfs(k,1));
  
  if(aa == 0)
    aa = 1; 
  end
  bb = floor(winplusfs(k,2));
  
  if afterStim 
    seg = strcat('_END_SEG', num2str(j));
  else
    seg = strcat('_SEG', num2str(j));
  end
  msize = size(data.EEEG.data, 2);
  disp(strcat('bb ', num2str(bb), ' msize ', num2str(msize)));
  if(bb < msize)
    fname = strrep(curName, '/', '_');
    sname = strcat(saveDir, '/', fname, '_', 'END_SEG', num2str(j), '_EEG.txt')
    dlmwrite(sname, data.EEEG.data(1:6, aa:bb));
    sname = strcat(saveDir,'/', fname, seg , '_LFFP.txt')
    dlmwrite(sname, data.LFFP.data(1:6, aa:bb),'\t');
  end
end
